### ISSUE TITLE
README update needed for CommonJS usage in v4.0.1

### ISSUE THREAD

**Issue by michaelcais** [jonschlinkert/get-value#35]
Hi, and thank you for maintaining this package!

After updating from v3.0.1 to v4.0.1, I received the error `get is not a function` and noticed that the package now uses an ES module default export. When using CommonJS with `require`, the default export must be accessed via the `.default` property:

`const get = require('get-value').default;`

The **README** still shows the previous CommonJS usage:

`const get = require('get-value');`

It would be helpful if the **README** could be updated to reflect this change for CommonJS users using the latest package. Thanks for considering!
